name: Package Single Executable Application, SEA

on:
  workflow_call:
    inputs:
      SEA_NAME:
        required: true
        type: string
      SEA_PATH:
        required: true
        type: string  
  workflow_dispatch:
    inputs:
      SEA_NAME:
        required: true
        type: string
        default: 'pullcraft'
      SEA_PATH:
        required: true
        type: string
        default: 'build/assets'
jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate version and update source
      run: npm run version src/bin/pullcraft.ts

    - name: Build project
      run: npm run build

    - name: Package SEA
      run: npm run package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.SEA_NAME }}-${{ matrix.os }}
        path: ${{ inputs.SEA_PATH }}/${{ inputs.SEA_NAME }}*
        if-no-files-found: error

    - name: List dist directory (for debugging)
      run: ls -R dist