name: Package Single Executable Application, SEA

on:
  workflow_call:
    inputs:
      SEA_NAME:
        required: true
        type: string
      SEA_PATH:
        required: true
        type: string  
  workflow_dispatch:
    inputs:
      SEA_NAME:
        required: true
        type: string
        default: 'pullcraft'
      SEA_PATH:
        required: true
        type: string
        default: 'build/assets'
jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #  windows-latest
        include:
          - os: ubuntu-latest
            asset_name: pullcraft-linux-x64
          # - os: windows-latest
          #   asset_name: pullcraft-win-x64.exe
          - os: macos-latest
            asset_name: pullcraft-macos-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # 0 depth because history is needed to get versions

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install

    - run: npx release-it --dry-run

    - name: Generate version and update source
      run: npm run inject-version

    - name: Build project
      run: npm run build

    - name: Print first 20 lines of pullcraft.ts
      run: head -n 20 ./src/bin/pullcraft.ts
      
    - name: Package SEA
      run: npm run package

    - name: List artifacts
      run: cd build/assets/; ls -la

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ inputs.SEA_PATH }}/${{ matrix.asset_name }}
        if-no-files-found: error

    - name: List dist directory (for debugging)
      run: ls -R dist