name: Publish

on: 
  workflow_dispatch:
  push: 
    branches:
      - main
      - beta
      - alpha

jobs:
  test:
    uses: ./.github/workflows/line_and_test.yml
  release:
    name: Release
    # needs: test
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run build --if-present
      - run: npx release-it --ci
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}     
  prerelease:
    # needs: test
    name: PreRelease
    if: github.ref_name != 'main'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run build --if-present
      - run: npx release-it --ci --preRelease=${{github.ref_name}}
