name: Publish

on: 
  workflow_dispatch:
  push: 
    branches:
      - main
      - beta
      - alpha
  pull_request:
    types: [closed]
    branches:
      - main
      - beta
      - alpha
jobs:
  lint_and_test:
    uses: ./.github/workflows/line_and_test.yml
 
  release:
    needs: lint_and_test
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')

    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifacts
          path: coverage
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run build --if-present
      # - name: Run tests and generate coverage
      #   run: npm run coverage
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
      - run: npx release-it --ci

  prerelease:
    needs: lint_and_test
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha'))

    name: PreRelease
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifacts
          path: coverage
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run build --if-present
      # - name: Run tests and generate coverage
      #   run: npm run coverage
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
      - run: npx release-it --ci --preRelease=${{github.ref_name}}
