name: Publish

on: 
  workflow_dispatch:
  push: 
    branches:
      - main
      - beta
      - alpha
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  pull_request:
<<<<<<< HEAD
=======
  pull_request:
>>>>>>> c302bb0 (tweak)
    types: [closed]
    branches:
      - main
      - beta
      - alpha
<<<<<<< HEAD
=======
    branches:
      - main # only works on PRs with base_ref=main and follows limits below
>>>>>>> 73f2099 (tweak)

jobs:
  lint_and_test:
    uses: ./.github/workflows/line_and_test.yml

=======
  # pull_request:
  #   branches:
  #     - main # only works on PRs with base_ref=main and follows limits below

jobs:
<<<<<<< HEAD
  test:
<<<<<<< HEAD
    name: Release Test
    uses: ./.github/workflows/line_and_test.yml#test
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
>>>>>>> 2be5c7c (tweak)
=======
    uses: ./.github/workflows/line_and_test.yml
>>>>>>> a4a4ca1 (tweak)
  release:
<<<<<<< HEAD
    needs: lint_and_test
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
=======
    needs: test
>>>>>>> 69d178f (tweak)
=======
  # test:
  #   uses: ./.github/workflows/line_and_test.yml
  release:
    # needs: test
>>>>>>> 75f47b1 (tweak)
=======
=======
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main
  #     - beta
  #     - alpha
>>>>>>> 5e0b1c9 (tweak)

jobs:
  lint_and_test:
    uses: ./.github/workflows/line_and_test.yml

  release:
    needs: lint_and_test
    if: |
<<<<<<< HEAD
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
>>>>>>> c302bb0 (tweak)
=======
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
>>>>>>> 5e0b1c9 (tweak)
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Download coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run build --if-present
      # - name: Run tests and generate coverage
      #   run: npm run coverage
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
      - run: npx release-it --ci

  prerelease:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    needs: lint_and_test
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha'))
=======
    # needs: test
>>>>>>> 4a38760 (tweak)
=======
    needs: test
>>>>>>> 69d178f (tweak)
=======
    # needs: test
>>>>>>> 75f47b1 (tweak)
=======
    needs: lint_and_test
    if: |
<<<<<<< HEAD
      (github.event_name == 'push' && (github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'beta' || github.event.pull_request.base.ref == 'alpha'))
>>>>>>> c302bb0 (tweak)
=======
      (github.event_name == 'push' && (github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha'))
>>>>>>> 5e0b1c9 (tweak)
    name: PreRelease
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Download coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run build --if-present
      # - name: Run tests and generate coverage
      #   run: npm run coverage
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
      - run: npx release-it --ci --preRelease=${{github.ref_name}}
